version: '3'

services:
      
  mediscreennoteapi:
    depends_on:
      - mongo
    image: mediscreennoteapi
    container_name: mediscreennoteapi
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_HOST = mongo
    networks:
      - local
      
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - local

networks:
  local:
    driver: bridge
